class Ring : HealthBonus
{
	override void Touch(Actor toucher)
	{
		// cash money
		// RLP (Gemini0)
		string moneyType = "RLP_Currency";
		class<Actor> moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 1); // idk how much rlp will give per coin or whatever ($1)
		// Pandora's Wrath (Gemini0, Mengo, JM2098)
		moneyType = "GWM_PandoraPoints";
		moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 5); // 5 points
		// BNDoom / any other mod with Zenny (Gemini0)
		moneyType = "Zenny";
		moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 25); // why you would EVER play BNDoom with this... i have no fucking idea (25 Zenny)
		// HXRTC (Hexereticdoom)
		moneyType = "BronzeCoinBonus";
		moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 1); // $25
		// DoomRLA Zeta-dimensional shop (Simon-v, Yholl)
		moneyType = "ZSCreditChip";
		moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 25); // 25 credits
		// Dino Crisis 2 Weapons (Dr_Cosmobyte)
		moneyType = "DC2BronzeCoin";
		moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 1); // 1000 points
		// Psychic (Xaser)
		moneyType = "BloodCoin25";
		moneyTypeExists = moneyType;
		if (moneyTypeExists)
			toucher.GiveInventory(moneyType, 1); // $25
	// and finally get touched after all that. GOD i hope this isnt an active detriment to performance
		Super.Touch(toucher);
	}
	// void A_AttractChase
	Default
	{
		Tag "Ring";
		+NOGRAVITY -MOVEWITHSECTOR +NOLIFTDROP +NOCLIP
		Inventory.MaxAmount 9999;
		Inventory.PickupMessage "";
		Inventory.PickupFlash "RingSparkle";
		Radius 16;
		Height 24;
	}
	States
	{
		Spawn:
			RING ABCDEFGHIJKLMNOPQRSTUVWX 1 /*A_AttractChase*/;
			Loop;
	}
}
class RingSparkle : PickupFlash
{
	Default
	{
		Radius 32;
		Height 32;
	}
	States
	{
		Spawn:
			SPRK ABCDABCDABCDABCD 1;
			Stop;
	}
}

class MarioCoin : Ring
{
	Default
	{
		Tag "Coin";
		+NOGRAVITY -MOVEWITHSECTOR +NOLIFTDROP +NOCLIP
		Inventory.PickupFlash "MarioCoinSparkle";
	}
	States
	{
		Spawn:
			COIN ABC 5 /*A_AttractChase*/;
			Loop;
	}
}
class MarioCoinSparkle : PickupFlash
{
	Default
	{
		Radius 32;
		Height 32;
	}
	States
	{
		Spawn:
			CPRK ABCD 5;
			Stop;
	}
}

class SpecialStageToken : Inventory // Make the Signpost check for this later.
{
	Actor child;
	override void PostBeginPlay()
	{
		child = Spawn("SpecialStageTokenBubble", self.pos);
		Super.PostBeginPlay();
	}
	override void Touch (Actor toucher) // why did this take like 30 minutes to figure out
	{
		child.Destroy();
		Super.Touch(toucher);
	}
	Default
	{
		Radius 8;
		Height 16;
		Inventory.MaxAmount 9999;
		Inventory.PickupMessage "";
		Inventory.PickupFlash "RingSparkle";
		+NOGRAVITY
	}
	States
	{
		Spawn:
			EMMY ABCDEFG 2 Bright;
			Loop;
	}
}
class SpecialStageTokenBubble : Actor
{
	Default
	{
		Radius 8;
		Height 16;
		+NOGRAVITY
		RenderStyle "Add";
	}
	States
	{
		Spawn:
			TOKE A -1;
			Stop;
	}
}