class Ring : HealthBonus
{
	Default
	{
		Tag "Ring";
		+NOGRAVITY -MOVEWITHSECTOR +NOLIFTDROP +NOCLIP
		Inventory.MaxAmount 9999;
		Inventory.PickupMessage "";
		Inventory.Icon "RINGA0";
		Inventory.PickupFlash "RingSparkle";
	}
	States
	{
		Spawn:
			RING ABCDEFGHIJKLMNOPQRSTUVWX 1;
			Loop;
	}
}

class RingSparkle : PickupFlash
{
	States
	{
		Spawn:
			SPRK ABCDABCDABCDABCD 1;
			Stop;
	}
}

// mario coin = COIN
// coin spark = CPRK