class SRB2KnucklesPlayer : SRB2PlayerTemplate
{
	Default
	{
		Speed 1.25;
		Player.DisplayName "Knuckles";
		Player.JumpZ 12;
		// Sorry, but you should make a new character class...
		// Unfortunately, due to SRB2's strange naming conventions,
		// you have to copy *all of this*.
	}
	States
	{
		Spawn:
			KNU0 A 105;
			Goto Tap;
		Tap:
			KNU0 BC 16;
			Loop;
		See:
		Walk:
			KNU0 DEFGHIJK 4;
			Loop;
		Jump: // either put this above Roll or Spring
		Roll:
			KNU0 LMNO 1;
			Loop;
		Spring:
			KNU0 P -1;
			Loop;
		Run:
			KNU0 QRST 2;
			Loop;
		Ability:
			KNU0 UV 2;
			Loop;
		Special:
			KNU0 WXYZ 6;
			Loop;
		ClimbStop:
			KNU0 W -1;
			Loop;
		Climb:
			KNU0 XYZY 5;
			Loop;
		Gasp:
			KNU0 [ 14;
			Goto Walk;
		Pain:
			KNU0 \ -1;
			Goto Spawn;
		Death:
			KNU0 ] 8 A_Fall;
			KNU0 ] 7;
			KNU0 ] -1;
			Loop;
		Teeter:
			KNU1 AB 12;
			Loop;
		Fall:
			KNU1 CD 2;
			Loop;
		Ride:
			KNU1 E -1;
			Loop;
		SuperStand:
			KNU0 U -1;
			Loop;
		SuperWalk:
			KNU0 UV 7;
			Loop;
		SuperFly:
			KNU0 WX 7;
			Loop;
		SuperTeeter:
			KNU0 Y 12;
			Loop;
		SuperPain:
			KNU0 Z -1;
			Loop;
		Melee:
		Missile:
			KNU0 X 8;
			Goto Spawn;
	}
}