class GoldBuzz : SRB2EnemyTemplate
{
	/*
	state A_BuzzFly()
	{
		if (self.bAMBUSH)
			return ResolveState(null);
		
		if (self.reactiontime)
			self.reactiontime--;
		
		// modify target threshold
		if (self.threshold)
		{
			if (!self.target || self.target.health <= 0)
				self.threshold = 0;
			else
				self.threshold--;
		}

		if (!self.target || !(self.target.bSHOOTABLE))
		{
			// look for a new target
			if (P_LookForPlayers(self, true, false))
				return ResolveState(null); // got a new target
			
//			self.vel.z = self.vel.y = self.vel.z = 0; // were one of these meant to be vel.x??
			self.vel.x = self.vel.y = self.vel.z = 0; // fixed it... hope it works okay
			return ResolveState("Spawn");
		}

		// turn towards movement direction if not there yet
		self.angle = R_PointToAngle2(self.x, self.y, self.target.x, self.target.y);

		if (self.target.health <= 0 || (!self.threshold && !P_CheckSight(self, self.target)))
		{
//			if ((multiplayer || netgame) && P_LookForPlayers(self, true, false))
//				return ResolveState(null); // got a new target

			self.vel.x = self.vel.y = self.vel.z = 0;
			return ResolveState("Spawn"); // Go back to looking around
		}

		// If the player is over 3072 fracunits away, then look for another player
		if (P_AproxDistance(P_AproxDistance(self.target.x - self.x, self.target.y - self.y),
			self.target.z - self.z) > 3072) // originally 3072*FRACUNIT... idk
		{
//			if ((multiplayer || netgame)
//				P_LookForPlayers(self, true, false); // maybe get a new target
			return ResolveState(null);
		}

		// chase towards player
		{
			int dist, realspeed;

			if (gameskill <= sk_easy)
				realspeed = FixedDiv(self.info.speed,5/2);
			else if (gameskill < sk_hard)
				realspeed = self.info.speed;
			else
				realspeed = FixedMul(self.info.speed,5/2);
			
			dist = P_AproxDistance(P_AproxDistance(self.target.x - self.x,
				self.target.y - self.y), self.target.z, self.z);

			if (dist < 1)
				dist = 1;
			
			self.vel.x = FixedMul(FixedDiv(self.target.x - self.x, dist), realspeed);
			self.vel.y = FixedMul(FixedDiv(self.target.y - self.y, dist), realspeed);
			self.vel.z = FixedMul(FixedDiv(self.target.z - self.z, dist), realspeed);

			if (self.z+self.vel.z >= self.waterbottom && self.watertop > self.floorz
				&& self.z+self.vel.z > self.watertop - 256) // originally 256*FRACUNIT... idk
			{
				self.vel.z = 0;
				self.z = self.watertop;
			}
		}
	}
	*/
	Default
	{
		Tag "Gold Buzz";
		Health 20;
		ReactionTime 2;
		PainChance 3072; // what the fuck?
		Speed 4;
		Radius 20;
		Height 24;
		Mass 100;
		DropItem "Flicky";
		+NOGRAVITY
//		+SLIDESONWALLS
		+FLOAT
	}
	States
	{
		Spawn:
			BUZZ AB 2 A_Look;
			Loop;
		See:
//			BUZZ AB 2 A_BuzzFly;
			BUZZ AB 2 A_Chase;
			Loop;
	}
}
class RedBuzz : GoldBuzz
{
	Default
	{
		Tag "Red Buzz";
	}
	States
	{
		Spawn:
			RBUZ AB 2 A_Look;
			Loop;
		See:
//			RBUZ AB 2 A_BuzzFly;
			RBUZ AB 2 A_Chase;
			Loop;
	}
}

class Deton : SRB2EnemyTemplate // JANK AS FUCK, FIX LATER PLEASE
{
	action void A_DetonChase()
	{
		// okay so i'm not rewriting the whole original function.
		// instead i'm gonna use the new version of A_Chase...
		// maybe find a nice way to make it turn normally
		// 6/13/24: holy shit maybe i really just should find a new way. this sucks. also +SPECIAL this later
		if (target)
			self.Speed = (target.Speed*3)*4;
		A_Chase("Death");
	}
	Default
	{
		-SOLID
		+MISSILE
		+NOGRAVITY
		+FLOAT
		+SHOOTABLE
		+MISSILEMORE
		+MISSILEEVENMORE
		+NOEXPLODEFLOOR
		+AMBUSH // maybe?? just so they don't chase you down
		Health 1;
		Damage 96;
		ReactionTime 1;
		Radius 20;
		Height 32;
		DropItem "Flicky";
		SeeSound "sfx/deton";
	}
	States
	{
		Spawn:
			DETN A 35 A_Look;
			Loop;
		See:
			DETN ABCDEFGHGFEDCB 1 A_DetonChase;
			Loop;
		Death:
			TNT1 A 0 A_Explode();
			Goto Super::Death;
	}
}