
class AmbientWaterA : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr1", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterB : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr2", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterC : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr3", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterD : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr4", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterE : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr5", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterF : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr6", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterG : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr7", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class AmbientWaterH : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/amwtr8", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}

class RandomAmbient : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/ambint", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}
class RandomAmbient2 : SRB2SceneryTemplate
{
	States
	{
		Spawn:
			TNT1 A 1 A_StartSound("sfx/ambin2", CHAN_AUTO, CHANF_OVERLAP|CHANF_LOOPING);
			Loop;
	}
}