class DSZGargoyle : Actor
{
	Default
	{
		Speed 21;
		Radius 16;
		Height 40;
		Mass 100;
		ActiveSound "sfx/statu2";
		+PUSHABLE
		+SOLID
		// +SLIDESONWALLS // originally MF_SLIDEME
	}
	States
	{
		Spawn:
			GARG A -1;
			Stop;
	}
}

class DSZSeaweed : Actor
{
	Default
	{
		Radius 24;
		Height 56;
		// I'll keep this part in anyway I guess
		+NOCLIP
		+NOBLOCKMAP
		+NOGRAVITY
		+NOINTERACTION
	}
	States
	{
		Spawn:
			SEWE ABCDEF 5; // Originally the first state had a -1 duration? Whatever.
			Loop;
	}
}

class DSZWaterDrip : Actor
{
	Default
	{
		Radius 1;
		Height 15;
		Mass 4;
		+NOCLIP
		+NOBLOCKMAP
		+SPAWNCEILING
		+NOGRAVITY
	}
	States
	{
		Spawn:
			DISS AAA 35; // Three seconds
			DRIP AB 2;
			DRIP C 2 A_SpawnItemEx("DSZWaterDrop");
			Loop;
	}
}
class DSZWaterDrop : Actor
{
	Default
	{
		DeathSound "sfx/wdrip1";
		Radius 2;
		Height 8;
		Mass 8;
		+MISSILE
	}
	States
	{
		Spawn:
			DRIP D -1;
			Stop;
		Death:
			TNT1 A 0 A_Scream;
			DRIP EF 1;
			Stop;
	}
}

class DSZCoral1 : Actor
{
	Default
	{
		Radius 8;
		Height 16;
		+NOCLIP
		+NOBLOCKMAP
		+NOGRAVITY
		+NOINTERACTION
	}
	States
	{
		Spawn:
			CRL1 A -1;
			Stop;
	}
}
class DSZCoral2 : DSZCoral1
{
	States
	{
		Spawn:
			CRL2 A -1;
			Stop;
	}
}
class DSZCoral3 : DSZCoral1
{
	States
	{
		Spawn:
			CRL3 A -1;
			Stop;
	}
}

class DSZBlueCrystal : Actor
{
	Default
	{
		Radius 8;
		Height 16;
		+NOCLIP
		+NOBLOCKMAP
		+NOGRAVITY
		+NOINTERACTION
	}
	States
	{
		Spawn:
			BCRY A -1;
			Stop;
	}
}