class Thok : Actor
{
	Default
	{
		RenderStyle "Translucent";
		Alpha 0.5;
		+NOINTERACTION
	}
	States
	{
		Spawn:
			THOK A 8;
			Stop;
	}
}

class SRB2Splash : Actor
{}

class CeilingSpike : Actor
{
	Default
	{
		Radius 8;
		Height 42;
		+SOLID
		+SPAWNCEILING
		+NOGRAVITY
	}
	States
	{
		Spawn:
			DSPK A -1; // so cool
			Stop;
	}
}
class FloorSpike : Actor
{
	Default
	{
		// why?
		Radius 8;
		Height 42;
		// it literally is set to be intangible...?
		// I'll keep this part in anyway I guess
		+NOBLOCKMAP
		+NOGRAVITY
		+NOINTERACTION
	}
	States
	{
		Spawn:
			USPK A -1; // so cool
			Stop;
	}
}

class Fan : Actor
{
	Default
	{
		Radius 16;
		Height 8;
		Mass 100;
		+SOLID
	}
	States
	{
		Spawn:
			FANS ABCDE 1;
			Loop;
	}
}